mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

admin.site.site_header = "nFactorial School Dashboard 💎"

urlpatterns = [
    #
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    #
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/details", views.detail, name="detail"),
    path("<int:question_id>/vote", views.vote, name="vote"),
    path("<int:question_id>/results", views.results, name="results"),
    path("questions/", views.add_question, name="question"),
    path(
        "questions/<int:question_id>",
        views.QuestionEditView.as_view(),
        name="question_edit",
    ),
    path("sign-up/", views.sign_up, name="sign_up"),
    path("<int:question_id>/delete", views.delete_question, name="delete"),


    path("api/", views.api_index, name="api_index"),
    path("api/post", views.api_post, name="api_post"),
    # path("api/questions/<int:pk>/", views.api_question_detail, name="api_question_detail"),
    path("api/questions/<int:pk>/", views.QuestionDetailView.as_view(), name="api_question_detail"),
    path("api/questions/", views.QuestionList.as_view(), name="api_question_list"),
]

polls/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        if self.pub_date > timezone.now():
            return False

        return self.pub_date >= timezone.now() - timedelta(hours=24)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField()

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_text"]


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]

polls/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import View
from rest_framework import generics, mixins, status
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.decorators import (
    api_view,
    authentication_classes,
    permission_classes,
)
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import QuestionForm, SignUpForm
from .models import Choice, Question
from .serializers import QuestionSerializer


@api_view(["GET"])
# @authentication_classes([TokenAuthentication, SessionAuthentication])
@permission_classes([IsAuthenticated])
def api_index(request):
    print(request.user.username)
    questions = Question.objects.all()
    serializer = QuestionSerializer(questions, many=True)

    return Response(serializer.data, status=418)


@api_view(["POST"])
def api_post(request):
    serializer = QuestionSerializer(data=request.data)
    if serializer.is_valid():
        question = serializer.save()
        return Response({"detail": "save success", "question_id": question.id})
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# @api_view(['GET', 'PUT', 'DELETE'])
# def api_question_detail(request, pk):
#    try:
#        question = Question.objects.get(pk=pk)
#    except Question.DoesNotExist:
#        return Response(status=status.HTTP_404_NOT_FOUND)

#    if request.method == 'GET':
#        serializer = QuestionSerializer(question)
#        return Response(serializer.data)

#    elif request.method == 'PUT':
#        serializer = QuestionSerializer(question, data=request.data)
#        if serializer.is_valid():
#            serializer.save()
#            return Response(serializer.data)
#        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#    elif request.method == 'DELETE':
#        question.delete()
#        return Response(status=status.HTTP_204_NO_CONTENT)

# class QuestionDetailView(APIView):
#     def get_object(self, pk):
#        try:
#            return Question.objects.get(pk=pk)
#        except Question.DoesNotExist:
#            return None

#     def get(self, request, pk):
#         question = self.get_object(pk)
#         if question is None:
#             return Response(status=status.HTTP_404_NOT_FOUND)
#         serializer = QuestionSerializer(question)
#         return Response(serializer.data)
    
#     def put(self, request):
#         return Response({})
    
#     def delete(self, request):
#         return Response({})

# class QuestionDetailView(mixins.RetrieveModelMixin,
#                          mixins.UpdateModelMixin,
#                          mixins.DestroyModelMixin,
#                          generics.GenericAPIView):
#     queryset = Question.objects.all()
#     serializer_class = QuestionSerializer

#     def get(self, request, *args, **kwargs):
#         return self.retrieve(request, *args, **kwargs)

#     def put(self, request, *args, **kwargs):
#         return self.update(request,*args, **kwargs)

#     def delete(self, request, *args, **kwargs):
#         return self.destroy(request,*args, **kwargs)

class QuestionDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

# class QuestionList(mixins.ListModelMixin,
#                   mixins.CreateModelMixin,
#                   generics.GenericAPIView):
#    queryset = Question.objects.all()
#    serializer_class = QuestionSerializer

#    def get(self, request, *args, **kwargs):
#        return self.list(request, *args, **kwargs)

#    def post(self, request, *args, **kwargs):
#        return self.create(request, *args, **kwargs)

class QuestionList(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


@login_required(login_url="/login/")
def index(request):
    questions = (
        Question.objects.filter(pub_date__lte=timezone.now())
        .order_by("-pub_date")
        .all()
    )
    context = {"questions": questions}
    return render(request, "polls/index.html", context)


# Create your views here.
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id, pub_date__lte=timezone.now())
    context = {"question": question}
    return render(request, "polls/detail.html", context)


def vote(request, question_id):
    choice_id = int(request.POST["choice"][0])

    choice = get_object_or_404(Choice, pk=choice_id)
    choice.votes += 1
    choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "polls/results.html", context)


@login_required(login_url="/login/")
@permission_required("polls.add_question", login_url="/login/")
def add_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return HttpResponseRedirect(reverse("polls:index"))
    else:
        form = QuestionForm()
    return render(request, "polls/question.html", {"form": form})


class QuestionEditView(View):
    def get(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        form = QuestionForm(instance=question)
        return render(
            request,
            "polls/question_edit.html",
            {"form": form, "question_id": question_id},
        )

    def post(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)

        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("polls:detail", args=(question_id,)))


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()

            # добавить в default
            group = Group.objects.get(name="default")
            group.user_set.add(user)

            login(request, user)
            return redirect(reverse("polls:index"))
    else:
        form = SignUpForm()

    return render(request, "registration/sign_up.html", {"form": form})


def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        if request.user == question.author or request.user.has_perm(
            "polls.delete_question"
        ):
            question.delete()
    return redirect(reverse("polls:index"))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Голосования nfactorial | {% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Голосования nfactorial</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/questions">Home</a>
                    </li>
                    
                    {% if user.is_authenticated %}
                    <span class="navbar-text">
                        Авторизован как @{{ user.username }}
                    </span>
                    
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" href="{% url 'logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-outline-primary" href="{% url 'login' %}">Войти</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %} {{ question.question_text }} {% endblock %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
       
        <h1>{{ question.question_text }}</h1>
       
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
     
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
       
        <input type="submit" value="Vote">
     </form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block title %} Список вопросов {% endblock %}

{% block content %}
    <ol>
        {% for question in questions %}
            <div class="card mt-2">
                <div class="card-header"><strong>@{{ question.author.username }}</strong></div>
                <div class="card-body d-flex flex-row justify-content-between">
                  <div>
                    <h5 class="card-title">
                        <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
                    </h5>
                  </div>
                  <div>
                    {% if user == question.author or perms.polls.delete_question %}
                        <form action="{% url 'polls:delete' question.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" >Удалить</button>
                        </form>
                    {% endif %}
                  </div>
                </div>
                <div class="card-footer text-muted">{{question.pub_date}}</div>
              </div>

        {% empty %}
            <p>Нет голосований</p>
        {% endfor %}
    </ol>
{% endblock %}

polls/templates/polls/question.html
{% extends "polls/base.html" %}

{% block title %} Contact {% endblock %}

{% block content %}

    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}


    <form action="{% url 'polls:question' %}" method="post">
        {% csrf_token %}
        
        {{ form }}
        
        <input type="submit" value="Добавить">
     </form>
{% endblock %}

polls/templates/polls/question_edit.html
{% extends "polls/base.html" %}

{% block title %} Contact {% endblock %}

{% block content %}

    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}


    <form action="{% url 'polls:question_edit' question_id %}" method="post">
        {% csrf_token %}
        
        {{ form }}
        
        <input type="submit" value="Vote">
     </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block title %} {{ question.question_text }} {% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    
    <ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} | {{ choice.votes }}
        </li>
    {% endfor %}
    </ul>
{% endblock %}